"""empty message

Revision ID: f3b9ade3189a
Revises: 277104b579cd
Create Date: 2026-05-25 19:14:41.100291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b9ade3189a'
down_revision = '277104b579cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('video_url')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
